name: everyday vercel deployment

on:
  schedule:
    - cron:  '00 12 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          vercel-org-id: ${{ secrets.ZEIT_ORG_ID }}
          vercel-project-id: ${{ secrets.ZEIT_PROJECT_ID}}
